---
name: Version Bumper Action
author: TomerFi
description: Automated semantic version bumps based on conventional commits
branding:
  icon: package
  color: gray-dark
inputs:
  source:
    description: Source for the bump, any semver string or 'git' to fetch from tags.
    required: false
    default: git
  bump:
    description: Target bump, 'major' | 'minor' | 'patch' | 'auto'. An 'auto' bump only works with a 'git' source.
    required: false
    default: auto
  label:
    description: Development iteration build label. Defaults to '-dev'.
    required: false
    default: -dev
  path:
    description: When source is 'git', set folder in the git. Defaults to running workspace.
    required: false
    default: ${{ github.workspace }}
  # backward compatibility, will eventually be removed
  folder:
    description: DEPRECATED Please use 'path'.
    required: false
  bumpoverride:
    description: DEPRECATED Please use 'bump'.
    required: false
outputs:
  current:
    description: The original version.
  bump:
    description: The bump performed.
  next:
    description: The next version.
  dev:
    description: The next development iteration version.
  bump_object:
    description: The original object returned from the version-bumper tool.
  # segregated version parts
  major_part:
    description: The major part of the next version.
  minor_part:
    description: The minor part of the next version.
  patch_part:
    description: The patch part of the next version.
  dev_patch_part:
    description: The patch part of the development iteration.
  # backward compatibility, will eventually be removed
  new_version:
    description: DEPRECATED Please use 'next'.
  next_dev_iteration:
    description: DEPRECATED Please use 'dev'.
  patch_next_dev:
    description: DEPRECATED Please use 'dev_patch_part'.
runs:
  using: node20
  main: dist/action.js
