---
name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - '.dist/**'
      - 'action.js'
      - 'action.yml'
      - 'package.json'
      - 'package-lock.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@13465d022aa41c282f730be17574b5ce692d0186  # v1.78.1
      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@51f63319f592f97930c73d9c46184d20bd206393  # v.3.0.0

      - name: Ensure assistant files are linked
        uses: tomerfi/aicfg/link@7a71c5c7e0d8d9ebdd4a2e9212c9bb04a49c687f # 0.2.0
        with:
          source: agents
          target: claude-code

  test:
    needs: lint
    uses: ./.github/workflows/test_action.yml
