---
name: Release

on:
  workflow_dispatch:
    inputs:
      tweet:
        description: "Tweet new release?"
        required: false
        default: "yes"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Release new version
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Eat own dogfood
        id: bumper
        uses: ./
        with:
          changelog: true

      - name: Release to GitHub
        id: gh_release
        uses: ncipollo/release-action@v1.8.10
        with:
          bodyFile: changelog-${{ steps.bumper.outputs.new_version }}.md
          tag: ${{ steps.bumper.outputs.new_version }}

      - name: Update usage example
        run: >
          sed -i
          's/uses\: tomerfi\/version-bumper-action@.*/uses\: tomerfi\/version-bumper-action@${{ steps.bumper.outputs.new_version }}/g'
          .github/README.md

      - name: Configure git
        run: |
          git config --global user.name "version-bumper-action"
          git config --global user.email "noreply@version-bumper-action.tomfi.info"

      - name: Push modifications
        run: |
          git add .github/README.md
          git commit -m "docs: update README usage section with ${{ steps.bumper.outputs.new_version }} [skip ci]"
          git push

      - name: Tweet new release
        if: ${{ github.event.inputs.tweet == 'yes' }}
        uses: lazy-actions/tweet-action@1.0.1
        with:
          oauth_consumer_key: ${{ secrets.TWITTER_API_KEY }}
          oauth_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          oauth_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          oauth_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          message: |
            🚀🎉 Version Bumper Action ${{ steps.bumper.outputs.new_version }} has been released! 🎉🚀
            ${{ steps.gh_release.outputs.html_url }}

            #version_bumper_action
