---
name: Release

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Release title (blank for tag)"
        required: false
      bump:
        description: "Bump type (major/minor/patch/auto)"
        default: "auto"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: deployment
    name: Release new version
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Eat own dogfood
        id: bumper
        uses: ./
        with:
          bump: ${{ github.event.inputs.bump }}

      - name: Create a release name
        id: release_name
        uses: actions/github-script@v7
        with:
          script: |
            var retval = '${{ steps.bumper.outputs.next }}'
            if ('${{ github.event.inputs.title }}') {
              retval = retval.concat(' - ${{ github.event.inputs.title }}')
            }
            core.setOutput('value', retval)

      - name: Create a release
        id: gh_release
        uses: actions/github-script@v7
        with:
          script: |
            const repo_name = context.payload.repository.full_name
            const response = await github.request('POST /repos/' + repo_name + '/releases', {
              tag_name: '${{ steps.bumper.outputs.next }}',
              name: '${{ steps.release_name.outputs.value }}',
              generate_release_notes: true
            })
            core.setOutput('html_url', response.data.html_url)

      - name: Update usage example
        run: >
          sed -i
          's/uses\: tomerfi\/version-bumper-action@.*/uses\: tomerfi\/version-bumper-action@${{ steps.bumper.outputs.next }}/g'
          README.md

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push modifications
        run: |
          git add README.md
          git commit -m "docs: update README usage section with ${{ steps.bumper.outputs.next }} [skip ci]"
          git push
