---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  stage:
    runs-on: ubuntu-latest
    environment: staging
    name: Test the action
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create initial testing repository
        run: |
          mkdir ${{ github.workspace }}/tmprepo
          cd ${{ github.workspace }}/tmprepo
          git init
          echo "blabla" > file
          git add file
          git commit -m "build: initial commit"

      - name: Run local action
        id: bumper
        uses: ./
        with:
          label: .tst
          changelog: true
          folder: tmprepo

      - name: Verify patch bump
        if: >
          steps.bumper.outputs.new_version != '1.0.0' ||
          steps.bumper.outputs.next_dev_iteration != '1.0.1.tst'
        uses: actions/github-script@v5
        with:
          script: core.setFailed('bump not working correctly')

      - name: Verify changelog file exists
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: tmprepo/changelog-1.0.0.md
          allow_failure: true

      - name: Cleanup
        if: always()
        run: rm -rf ${{ github.workspace }}/tmprepo
