---
name: Update readme

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    environment: deployment
    name: Update readme usage example with latest release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Update usage example
        run: >
          sed -i
          's/uses\: tomerfi\/version-bumper-action@.*/uses\: tomerfi\/version-bumper-action@${{ github.event.release.tag_name }}/g'
          .github/README.md

      - name: Configure git
        run: |
          git config --global user.name "version-bumper-action"
          git config --global user.email "noreply@version-bumper-action.tomfi.info"

      - name: Push modifications
        run: |
          git add .github/README.md
          git commit -m "docs: update README usage section with ${{ github.event.release.tag_name }} [skip ci]"
          git push
